package guideline

dialect  "mvel"

import cdss.kb.core.patient.Patient;
import cdss.kb.core.patient.MedicalRecord
import cdss.kb.core.patient.EpidemicHistory;
import java.util.ArrayList
import cdss.kb.core.patient.Diagnosis
import cdss.kb.core.patient.PhysicalSign
import cdss.kb.core.patient.Symptom
import cdss.kb.core.patient.ImgExamResult
import cdss.kb.core.patient.*

import cdss.kb.core.RuleIdentification
import java.util.Date
import java.text.SimpleDateFormat


rule "轻型"
 salience 910
  lock-on-active true
    agenda-group "诊断-分型"
 when
    $p: Patient($epidemicHistory: epidemicHistory, $sypmtomList: symptomList,
             $physicalSignList: physicalSignList, $imgExamResultList: imgExamResultList,
             $labTestResultList:labTestResultList);
    $r: RuleIdentification($ruleIdentification: RuleIdentification);
    $sypmtom: Symptom(text == "The clinical symptoms were mild" ) from $sypmtomList;
    ArrayList(size>0) from collect(ImgExamResult(description == "There was no sign of pneumonia on imaging" && itemName=="Chest CT" ) from $imgExamResultList);
 then
 System.out.println("轻型");

    if($r.getRuleIdentification().contains("确诊")){
        $r.getRuleIdentification().add("轻型");
    }
  end

rule "普通型"
 salience 900
  lock-on-active true
    agenda-group "诊断-分型"
 when
    $p: Patient($epidemicHistory: epidemicHistory, $sypmtomList: symptomList,
             $physicalSignList: physicalSignList, $imgExamResultList: imgExamResultList,
             $labTestResultList:labTestResultList);
    $r: RuleIdentification($ruleIdentification: RuleIdentification);
//    $sypmtom: Symptom(text == "发热" || text == "有呼吸道症状" ) from $sypmtomList;
    ArrayList(size>0) from collect (ImgExamResult(description == "With the above imaging characteristics of pneumonia" && itemName=="Chest CT" ) from $imgExamResultList);
 then
 System.out.println("普通型");
    c1 = $r.getRuleIdentification().contains("发热") || $r.getRuleIdentification().contains("有呼吸道症状");
    if($r.getRuleIdentification().contains("确诊")&&c1){
        $r.getRuleIdentification().add("普通型");
    }
  end

rule "呼吸频次"
    salience 890
      lock-on-active true
      agenda-group "诊断-分型"
   when
      $p: Patient($epidemicHistory: epidemicHistory, $sypmtomList: symptomList,
               $physicalSignList: physicalSignList, $imgExamResultList: imgExamResultList,
               $labTestResultList:labTestResultList);
      $r: RuleIdentification($ruleIdentification: RuleIdentification);
      resp_G: ArrayList(size>0) from collect (PhysicalSign(itemName=="RR") from $physicalSignList)
      $patientInfo: PatientInfo();
   then
 System.out.println("呼吸频次");
      int num = Integer.parseInt($p.getPhysicalSign("RR").getValue());
      Date now = new Date();
      long num_month_1  = (now.getTime()-$patientInfo.getDateOfBirth().getTime())/(60*60*24*30);
      long num_month = num_month_1/1000;
      if(num_month<2){
          if(num>60||num==60){
              System.out.println(num_month+"呼吸频次过高->1-2 months old.");
              $r.getRuleIdentification().add("呼吸频次过高");
          }
      }else if(num_month<12){
          if(num>50||num==50){
              System.out.println(num_month+"呼吸频次过高->2-12 months old.");
              $r.getRuleIdentification().add("呼吸频次过高");
          }
      }else if(num_month/12.0 < 5){
          if(num>40||num==40){
              System.out.println(num_month+"呼吸频次过高->1-5 years old.");
              $r.getRuleIdentification().add("呼吸频次过高");
          }
      }else {
          if(num>30||num==30){
              System.out.println(num_month+"呼吸频次过高->5 years old.");
              $r.getRuleIdentification().add("呼吸频次过高");
          }
      }
    end

rule "指氧饱和度"
  salience 880
        lock-on-active true
        agenda-group "诊断-分型"
 when
    $p: Patient($epidemicHistory: epidemicHistory, $sypmtomList: symptomList,
             $physicalSignList: physicalSignList, $imgExamResultList: imgExamResultList,
             $labTestResultList:labTestResultList);
    $r: RuleIdentification($ruleIdentification: RuleIdentification);
    resp_G: ArrayList(size>0) from collect (PhysicalSign(itemName=="SaO2") from $physicalSignList)
    $patientInfo: PatientInfo();
 then
  System.out.println("指氧饱和度");
      Date now = new Date();
      long num_month_1  = (now.getTime()-$patientInfo.getDateOfBirth().getTime())/(60*60*24*30);
      long num_month = num_month_1/1000;

    Float num = Float.parseFloat($p.getPhysicalSign("SaO2").getValue());
    if(num_month/12.0>14){
        if(num<93||num==93){
            System.out.println(num_month+"指氧饱和度过低");
            $r.getRuleIdentification().add("指氧饱和度过低");
        }
    }else {
        if(num<92||num==92){
            System.out.println(num_month+"指氧饱和度过低");
            $r.getRuleIdentification().add("指氧饱和度过低");
        }
    }
  end

rule "PaO2/FiO2"
  salience 870
  lock-on-active true
  agenda-group "诊断-分型"
 when
    $p: Patient($epidemicHistory: epidemicHistory, $sypmtomList: symptomList,
             $physicalSignList: physicalSignList, $imgExamResultList: imgExamResultList,
             $labTestResultList:labTestResultList);
    $r: RuleIdentification($ruleIdentification: RuleIdentification);
    ArrayList(size>0) from collect (PhysicalSign(itemName=="PaO2") from $physicalSignList)
    ArrayList(size>0) from collect (PhysicalSign(itemName=="FiO2") from $physicalSignList)
 then
   System.out.println("PaO2/FiO2");

    Float num1 = Float.parseFloat($p.getPhysicalSign("PaO2").getValue());
    Float num2 = Float.parseFloat($p.getPhysicalSign("FiO2").getValue());
    Float localPressure = Float.parseFloat("736");
    Float num3 =(num1/num2)*(localPressure/760);
//    System.out.println(num3);
    if(num3<300||num3==300){
        $r.getRuleIdentification().add("PaO2/FiO2过低");
    }
    if((num3<80||num3==80)&&num2>0.9){
        $r.getRuleIdentification().add("氧合指数小于80");
    }
  end

rule "病灶明显进展"
 salience 860
 lock-on-active true
 agenda-group "诊断-分型"
 when
    $p: Patient($epidemicHistory: epidemicHistory, $sypmtomList: symptomList,
             $physicalSignList: physicalSignList, $imgExamResultList: imgExamResultList,
             $labTestResultList:labTestResultList);
    $r: RuleIdentification($ruleIdentification: RuleIdentification);
    $imgExamResult: ImgExamResult(description == " Chest imaging that shows obvious lesion progression within 24-48 hours >50%" && itemName=="Chest CT" ) from $imgExamResultList;
 then
   System.out.println("病灶明显进展");
    $r.getRuleIdentification().add("肺部影像学明显进展");
  end

rule "重型-儿童-辅助呼吸"
 salience 855
  lock-on-active true
    agenda-group "诊断-分型"
when
    $p: Patient($epidemicHistory: epidemicHistory, $sypmtomList: symptomList,
             $physicalSignList: physicalSignList, $imgExamResultList: imgExamResultList,
             $labTestResultList:labTestResultList, $orderList: orderList);
    $r: RuleIdentification($ruleIdentification: RuleIdentification);
    ArrayList(size>0) from collect (Symptom(text=="Labored breathing") from $sypmtomList);
    ArrayList(size>0) from collect (Symptom(text=="Cyanosis") from $sypmtomList);
    ArrayList(size>0) from collect (Symptom(text=="Intermittent apnea") from $sypmtomList);
then
    System.out.println("重型-儿童-辅助呼吸");
    $r.getRuleIdentification().add("辅助呼吸");
end

rule "重型-儿童-嗜睡惊厥"
 salience 854
  lock-on-active true
    agenda-group "诊断-分型"
when
    $p: Patient($epidemicHistory: epidemicHistory, $sypmtomList: symptomList,
             $physicalSignList: physicalSignList, $imgExamResultList: imgExamResultList,
             $labTestResultList:labTestResultList, $orderList: orderList);
    $r: RuleIdentification($ruleIdentification: RuleIdentification);
    ArrayList(size>0) from collect(Symptom(text=="Lethargy" || text=="Convulsions") from $sypmtomList);
then
    System.out.println("重型-儿童-嗜睡惊厥");
    $r.getRuleIdentification().add("嗜睡或惊厥");
end

rule "重型-儿童-拒食"
 salience 853
  lock-on-active true
    agenda-group "诊断-分型"
when
    $p: Patient($epidemicHistory: epidemicHistory, $sypmtomList: symptomList,
             $physicalSignList: physicalSignList, $imgExamResultList: imgExamResultList,
             $labTestResultList:labTestResultList, $orderList: orderList);
    $r: RuleIdentification($ruleIdentification: RuleIdentification);
    ArrayList(size>0) from collect(Symptom(text=="Difficulty feeding") from $sypmtomList);
    ArrayList(size>0) from collect(Symptom(text=="Signs of dehydration") from $sypmtomList);
then
    System.out.println("重型-儿童-拒食");
    $r.getRuleIdentification().add("拒食");
end

rule "重型-儿童"
 salience 851
  lock-on-active true
    agenda-group "诊断-分型"
 when
    $p: Patient($epidemicHistory: epidemicHistory, $sypmtomList: symptomList,
             $physicalSignList: physicalSignList, $imgExamResultList: imgExamResultList,
             $labTestResultList:labTestResultList, $orderList: orderList);
    $r: RuleIdentification($ruleIdentification: RuleIdentification);
    $patientInfo: PatientInfo();
 then
   System.out.println("重型-儿童");
   Date now = new Date();
   long num_1 = (now.getTime()-$patientInfo.getDateOfBirth().getTime())/(60*60*24*30);
   num = num_1/1000;
   c1 = $r.getRuleIdentification().contains("辅助呼吸");
   c2 = $r.getRuleIdentification().contains("呼吸频次过高");
   c3 = $r.getRuleIdentification().contains("指氧饱和度过低");
   c4 = $r.getRuleIdentification().contains("嗜睡或惊厥");
   c5 = $r.getRuleIdentification().contains("拒食");
   summary = c1 || c2 || c3 || c4 ||c5;
   c6 = false;
   if(num/12<14||num/12==14){
       c6 = true;
   }
   if($r.getRuleIdentification().contains("确诊")&&summary&&c6){
       $r.getRuleIdentification().add("重型");
       System.out.println(num+"重型-儿童-1");
   }

 end

rule "重型-成人"
 salience 850
  lock-on-active true
    agenda-group "诊断-分型"
 when
    $p: Patient($epidemicHistory: epidemicHistory, $sypmtomList: symptomList,
             $physicalSignList: physicalSignList, $imgExamResultList: imgExamResultList,
             $labTestResultList:labTestResultList);
    $r: RuleIdentification($ruleIdentification: RuleIdentification);
    $patientInfo: PatientInfo();
 then
   System.out.println("重型-成人");
   Date now = new Date();
   long num_1 = (now.getTime()-$patientInfo.getDateOfBirth().getTime())/(60*60*24*30);
   num = num_1/1000;
   c5 = false;
   if(num/12 >14){
       c5 = true;
   }

    c1 = $r.getRuleIdentification().contains("呼吸频次过高");
    c2 = $r.getRuleIdentification().contains("指氧饱和度过低");
    c3 = $r.getRuleIdentification().contains("PaO2/FiO2过低");
    c4 = $r.getRuleIdentification().contains("肺部影像学明显进展");
    summary = (c1 || c2 || c3 || c4) && c5;
//    summary = false;
    if($r.getRuleIdentification().contains("确诊")&&summary){
        $r.getRuleIdentification().add("重型");
        System.out.println(num+"重型-成人-1");
    }
  end

rule "危重型"
  salience 840
    lock-on-active true
      agenda-group "诊断-分型"
 when
    $p: Patient($epidemicHistory: epidemicHistory, $sypmtomList: symptomList,
             $physicalSignList: physicalSignList, $imgExamResultList: imgExamResultList,
             $labTestResultList:labTestResultList,$pastHistoryList: pastHistoryList);
    $r: RuleIdentification($ruleIdentification: RuleIdentification);
    $diagnosis_G : ArrayList( size > 0)
                             from accumulate( PastHistory($items: items) from $pastHistoryList,
                                              init( ArrayList arrayList=new ArrayList(); ),
                                              action( arrayList.addAll($items); ),
                                              result( arrayList ) );
   ArrayList(size>0) from collect (Diagnosis(itemName=="Respiratory failure"||itemName=="Shock"||itemName=="Other organ failure") from $diagnosis_G);
 then
   System.out.println("危重型");
    if($r.getRuleIdentification().contains("确诊")){
         $r.getRuleIdentification().add("危重型");
     }
  end

rule "诊断-分型-summary"
  salience 830
    lock-on-active true
      agenda-group "诊断-分型"
 when
    $p: Patient($epidemicHistory: epidemicHistory, $sypmtomList: symptomList,
             $physicalSignList: physicalSignList, $imgExamResultList: imgExamResultList,
             $labTestResultList:labTestResultList,$pastHistoryList: pastHistoryList);
    $r: RuleIdentification($ruleIdentification: RuleIdentification);
 then
   System.out.println("诊断-分型-summary");
    if($r.getRuleIdentification().contains("普通型")){
        $r.getRuleIdentification().remove("轻型");
    }
    if($r.getRuleIdentification().contains("重型")){
        $r.getRuleIdentification().remove("轻型");
        $r.getRuleIdentification().remove("普通型");
    }
    if($r.getRuleIdentification().contains("危重型")){
        $r.getRuleIdentification().remove("轻型");
        $r.getRuleIdentification().remove("普通型");
        $r.getRuleIdentification().remove("重型");
    }
    length = $p.getPastHistoryList().size();
    if($r.getRuleIdentification().contains("轻型")){
        $p.getPastHistoryList().get(length-1).getDiagnosis("新冠肺炎").setCategory("Mild");
    }
    if($r.getRuleIdentification().contains("普通型")){
        $p.getPastHistoryList().get(length-1).getDiagnosis("新冠肺炎").setCategory("Moderate");
    }
    if($r.getRuleIdentification().contains("重型")){
        $p.getPastHistoryList().get(length-1).getDiagnosis("新冠肺炎").setCategory("Severe");
    }
    if($r.getRuleIdentification().contains("危重型")){
        $p.getPastHistoryList().get(length-1).getDiagnosis("新冠肺炎").setCategory("Critical");
    }
    drools.setFocus("临床预警");
  end